version: 2
jobs:
  build:
    docker:
      - image: circleci/php:7.2-apache-stretch-node-browsers

    steps:
      - checkout
      - run: sudo apt update
      - run: sudo docker-php-ext-install zip

      # Composer
      - restore_cache:
          name: Restore composer cache
          keys:
            - composer-{{ checksum "composer.json" }}
            - composer-
      - run: composer install -n --prefer-dist
      - save_cache: 
          name: Store composer cache
          key: composer-{{ checksum "composer.json" }}
          paths:
            - vendor

      # Test for CI

      deploy:
    machine:
      enabled: true
    steps:
      - add_ssh_keys:
          fingerprints:
            - "6e:0a:6f:ba:8c:e9:fa:b0:fd:1c:cd:5f:38:49:7e:a9"
      - run:
          name: Deploy Over SSH
          command: ssh -tt root@103.200.20.171 "cd /var/www/html/laravel && git pull origin master"

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              master